"""salary currency is text not float

Revision ID: 06c910de918c
Revises: 2b95cd584064
Create Date: 2023-11-04 17:43:09.798729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c910de918c'
down_revision: Union[str, None] = '2b95cd584064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'base_salary_currency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=True,
               schema='offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'base_salary_currency',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               schema='offers',
               postgresql_using='base_salary_currency::double precision')
    # ### end Alembic commands ###
