"""base salary

Revision ID: 2b95cd584064
Revises: 74fc460b66f3
Create Date: 2023-11-04 17:33:09.865837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b95cd584064'
down_revision: Union[str, None] = '74fc460b66f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('base_salary_min', sa.Float(), nullable=True), schema='offers')
    op.add_column('offers', sa.Column('base_salary_max', sa.Float(), nullable=True), schema='offers')
    op.add_column('offers', sa.Column('base_salary_currency', sa.Float(), nullable=True), schema='offers')
    op.add_column('offers', sa.Column('base_salary_unit', sa.Text(), nullable=True), schema='offers')
    op.drop_column('offers', 'base_salary', schema='offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('base_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='offers')
    op.drop_column('offers', 'base_salary_unit', schema='offers')
    op.drop_column('offers', 'base_salary_currency', schema='offers')
    op.drop_column('offers', 'base_salary_max', schema='offers')
    op.drop_column('offers', 'base_salary_min', schema='offers')
    # ### end Alembic commands ###
