"""address locality can be null

Revision ID: 79e374599075
Revises: 06c910de918c
Create Date: 2023-11-04 17:48:24.449321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e374599075'
down_revision: Union[str, None] = '06c910de918c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'address_locality',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'address_locality',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='offers')
    # ### end Alembic commands ###
