# IMPORTANT!
# Changes in this file will not be reflected in qdrant if you don't uncomment a line that imports this config in docker-compose.yml.
# This is a copy of https://github.com/qdrant/qdrant/blob/master/config/production.yaml
# Use this file to make sure your values from config.yaml aren't being overwritten 
# (see config order in https://qdrant.tech/documentation/guides/configuration/)
log_level: INFO

service:
  host: 0.0.0.0
  http_port: 6333
  # Uncomment to enable gRPC:
  #grpc_port: 6334